Repository Wikia/mobile-wiki, pull requests merged in 2020-08, with the labels that each got.

#2287 ADEN-10357 Update ad-engine (12689aa540bc2d3259113a5bd57dfc86629e27b0)
  app/modules/ads/setup.js
  package-lock.json
  package.json
  tests/unit/modules/ads/ads/setup-test.js
Labels: Major change, enhancement

#2301 ADEN-10474 Expose ICBM sdk
  app/modules/ads/ad-context.js
  app/modules/ads/setup.js
  package-lock.json
  package.json
Labels: Minor change

#2300 PLATFORM-4944 | Add Performance monitoring
  app/routes/wiki-page.js
  app/utils/performance.js
  package-lock.json
  package.json
Labels: DON'T MERGE!

#2311 ADEN-10506 Fixing mobile-wiki asyncScriptsLoaded listener issue
  vendor/inline-scripts/mediawiki-scripts-handlers.js
Labels: Patch change, bug

#2303 ADEN-10456 Add MobileWiki Ads Platform
  app/modules/ads/core/experimental-ads.js
  app/modules/ads/core/promise-lock.js
  app/modules/ads/core/stable-ads.js
  app/modules/ads/index.js
  app/routes/application.js
  app/routes/search.js
  app/routes/wiki-page.js
  app/services/ads/ad-slot-builder.js
  app/services/ads/ads.js
  tests/integration/components/article-content-test.js
  tests/unit/components/ad-slot-test.js
Labels: Major change

#2344 ADEN-10540-2 Bump TrackingOptIn version
  app/services/smart-banner.js
  package-lock.json
  package.json
Labels: Patch change, enhancement
